apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskboard.fullname" . }}-frontend
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "taskboard.name" . }}-frontend
