apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskboard-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tanishq217/devsecops-pipeline.git
    targetRevision: HEAD
    path: helm/taskboard
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: taskboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
